### PR TITLE
Authentication and user creation by administrators

### PR DESCRIPTION
**Pull request by briaguya**
Implemented basic user management (creation) as per issue #6

### CODE REVIEW

**Comment by jcbpl** [comment]
@briaguya This looks pretty good overall. Some high-level thoughts/questions:

* Could you review the [Developer Guide](http://guides.austintexas.io/developer-guide/git/) (particularly the parts related to Deliberate Git and writing commit messages) and let me know if there's anything you'd like to discuss or modify? I'd like to be on the same page w/r/t commit history and message expectations.

* Do you have strong JS syntax/style preferences? I'd be interested in configuring [XO](https://github.com/sindresorhus/xo) or a similar linter. We should decide on spaces (generally my default) or tabs, and semicolons or none.

* I'd like to give some consideration to how we want to deal with CSS; having it in the same file as the component generally makes sense to me, and there are a number of different React-adjacent libs to do that. Let me know what you think.

* Do you think we should have separate repos for the different parts of ATXfloods, or one super-repo that contains different applications (admin client, web client, microservices)? I'm leaning toward one-repo, but there are pros and cons to both.

**Comment by briaguya** [comment]
Re: Git commit messages - I agree with the sentiment behind the commits, however, it does kind of put a few bumps in my dev flow. I commit fairly often and usually push on commit, and rewriting the history is kind of a pain. My personal preference would be to move away from a strong emphasis on robust commit messages, and towards smaller pieces for each PR. Then the commit log within each feature branch can be a little more sparse, as long as a full understanding of what was done for the feature branch comes across in the PR (and therefore the merge). I think this especially comes into play when linking to issues. By having well documented information within the project and issues on GH, we can reduce some of the pressure to use the commit log as documentation.

Re: JS syntax - I like 2 spaces and yes for semicolons. I'd be very happy to have a styler set up to ensure uniformity.

Re: CSS - I haven't gone too far into thinking about CSS yet, I'm open to try anything that doesn't paint us into a corner.

Re: Repos - I'm leaning towards a super repo. It's nice to be able to check out one thing and work on everything. If that becomes unwieldy we can always split up the repos in the future.

**Comment by jcbpl** [comment]
There's nothing wrong with committing and pushing often during development. Rewriting commits is an extra step, but it's not one that would I consider optional. In this PR, for instance, there are commits adding and removing over 1.5 million lines from node_modules. There is no way that those should be merged into master, because they have no bearing on the final implementation. That's an extreme example, but that kind of mid-course change happens all the time during development, and editing history is a way of consolidating and clarifying the decisions that were made to reduce future confusion.

Issues and PRs are good as far as they go, and as long as we continue to use GitHub to host our code. If we move to another Git host, all of that context is no longer available. More importantly, issues often resemble user stories (as they should), and don't reflect the thinking that goes into specific implementation decisions.

"Move PrivateRoute to it’s own file" (for example) isn't especially useful information to a future developer (and it communicates nothing about intent). What is useful is information about problems you ran into related to Cognito, how you solved them, what tradeoffs you made, etc. None of that is currently described by the commits in this PR. Anyone can see what happened by looking at a diff; the message needs to explain why it happened.

**Comment by briaguya** [comment]
I think I found a solution that more closely fits what both of us are looking for.

I think the main message I was trying to send was that we should try to make each PR small enough to be meaningful without relying on the git history for it. For example, with PR #9 the change itself is small enough to be squashed into a single commit message.

This way we can decide on a case by case basis with a PR if it's big enough to warrant multiple pieces having their own commit messages (such as this one is) or small enough to be squashed and merged.

Also, I'm going to go ahead and squash and merge PR #9 into this one before I do the amending to avoid merge issues.

**Pull request closed without merging**
